### ISSUE TITLE
YASL: Yet Another Serialization Library

### ISSUE THREAD

**Issue by AndyObtiva** [mcorino/firm#1]
I just wanted to note I've already created a Ruby gem that provides automatic marshalling support for Ruby objects (without crashing on certain objects like the Marshal library does):
- RubyGem: https://rubygems.org/gems/yasl
- GitHub: https://github.com/AndyObtiva/yasl

You might find it useful.

**Comment by mcorino** [comment]
Thanks. I'll have a look. The bidrectional reference issue is something I definitely  need to look  at.

**Comment by mcorino** [comment]
Thanks for the pointers.
I've just released v0.9.1 of the gem which now also handles cyclic references.
I've not reused any of your code but looking at it made me review and refactor my aliasing handling in view of cyclic references and now not only does FIRM handle cycles but also has much improved alias handling in general.
